### ISSUE TITLE
I want to add support for another languge

### ISSUE THREAD

**Issue by avrAhituv** [NodeBB/nodebb-plugin-category-notifications#10]
Hello!
I want to add support for another languge but I don't know how to do it..
enough to add a json file to languages dir?
and where do you define the extension to use in my languge?

thanks

**Comment by barisusakli** [comment]
Add a folder in https://github.com/NodeBB/nodebb-plugin-category-notifications/tree/master/languages and copy the file from en-GB then add your translations.

**Comment by avrAhituv** [comment]
tahnks!
but i want to add translation for content of email..
how do I do this generically, without manually replacing the file contents?

**Comment by avrAhituv** [comment]
Sorry..
I found that the email text can be changed in the admin panel.

Thanks!!
