### ISSUE TITLE
Not showing settings.

### ISSUE THREAD

**Issue by joaokrabbe** [NodeBB/nodebb-plugin-category-notifications#12]
Hi, I installed the plugin, restarted NodeBB, and no new field appeared in the admin settings.
I also tried to recompile NodeBB, but still nothing came up.

My version of NodeBB is v1.12.2

May can anyone help me?

**Comment by barisusakli** [comment]
Plugin should add a menu item into the ACP Plugins dropdown. Is it not available?

**Comment by joaokrabbe** [comment]
No, It's not available.

print: https://prnt.sc/pk8j5j

**Comment by barisusakli** [comment]
Works fine for me, do you have any errors/warnings in logs/output on startup?

**Comment by joaokrabbe** [comment]
Apparently the build was not being done correctly by the admin interface. When I built in the terminal, it worked.

Thank you for your help. I will close the topic.

**Comment by chocolate012** [comment]
same issue
