### ISSUE TITLE
The plugin does not consider user blocking settings

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/nodebb-plugin-category-notifications#17]
Hello, and thanks for this great plugin!
There is a problem that even though I blocked a user, and I do not see his topics in "unread" and "recent", if he opens a new topic in the category I follow, I do get an email update on it ... it no makes perfect sense - if I do not Want to see his topics, of course I do not need to get an email update on them ... :)
Thanks!
@barisusakli

**Comment by barisusakli** [comment]
Thanks for reporting. Please try with 3.1.0 and let me know.

**Comment by ShlomoCode** [comment]
@barisusakli Check for version 3.1.0 or the latest version - 3.1.1?

**Comment by ShlomoCode** [comment]
OK, I checked with the latest version that was available - 3.1.1
I really did not receive an email on a new topic from a user I blocked, great!
