### ISSUE TITLE
Design the emails from this plugin

### ISSUE THREAD

**Issue by ShlomoCode** [NodeBB/nodebb-plugin-category-notifications#18]
In the other emails sent from NodeBB, an email arrives with a design:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/78599753/162629479-f756f3b0-c0b9-408e-a179-ad3993db6064.png">
For some reason, in this plugin, an email arrives with plain text with no formatting:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/78599753/159750133-7108519a-79e8-4cb7-b925-9cfb2fdf23e4.png">
Is it possible to do something about it?
Thanks... :)

**Comment by ShlomoCode** [comment]
Even on the exact same topic, the email sent because of a follow-up of the user who published the topic, comes formatted, and the email that comes thanks to tracking the category, comes unformatted...

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-category-notifications/commit/1ead9388d07db7aceb3150769e1751a9dff717b1

**Comment by julianlam** [comment]
:smile: oh nice. Resolved this issue accidentally it seems.
