### ISSUE TITLE
Emails are no longer being sent for category notifications

### ISSUE THREAD

**Issue by Knuxchan** [NodeBB/nodebb-plugin-category-notifications#19]
This seemed to stop working sometime in early 2022. Checking the code, we noticed that no email sending mechanism is set, and it’s not falling through to sendmail. The front-end says the email sent successfully, but it never does and sendmail never gets the command to send an email. Other email notifications built-in to NodeBB are working fine.

**Comment by barisusakli** [comment]
@Knuxchan which version of the plugin are you using?

**Comment by Knuxchan** [comment]
Hi. We are using the latest version 3.1.1

**Comment by barisusakli** [comment]
Does it work on 3.1.0 or 3.0.6? There was a recent change to stop emails going out for blocked users wondering if that's causing this. #17

**Comment by Knuxchan** [comment]
Hey, my apologies. This was user error on my end. I noticed that my email was not verified in the administrator dashboard. After verifying my email in the dashboard, the Category Notifications plugin works great. I appreciate your quick response with this.
