### ISSUE TITLE
Double notifications.

### ISSUE THREAD

**Issue by zetas** [NodeBB/nodebb-plugin-category-notifications#2]
Is there any way to keep it from emailing someone who has a category "watched" and also gets replies emailed?

As it stands now if I reply to a thread it emails me whenever anyone replied but If i watch the category that thread is in I also get an email so I'm getting 2 emails for every post i reply to.

If it's not possible I understand and I'll just deal with it but It seems like it might be an easy fix.

**Comment by barisusakli** [comment]
I don't think watching/ignoring a category effects emails. But there is a setting in user/settings

![image](https://cloud.githubusercontent.com/assets/2583394/7618611/3483d318-f981-11e4-86e9-b09f799b898a.png)

You can disable that then you won't get the emails sent from core when someone replies to topics that you watch.

**Comment by zetas** [comment]
Right but what if someone replies to a thread in a category I'm not watching with this plugin? 

I **want** to get emailed on every reply, I'm the site admin and it's important i handle support responses however I also want to get emailed anytime activity happens in a particular category even if I'm not involved. 

Seems like double emailing should be something handled in the code and not by sacrificing functionality.

**Comment by barisusakli** [comment]
> I want to get emailed on every reply,

Yeah so disable that setting and subscribe to all categories with this plugin. Isn't that what you want?

**Comment by zetas** [comment]
Understood.
