### ISSUE TITLE
Unsubscribe 

### ISSUE THREAD

**Issue by NatashaSelvidge** [NodeBB/nodebb-plugin-category-notifications#23]
The class doesn't change to unsubscribe when the user clicks on it.

**Comment by barisusakli** [comment]
hey @NatashaSelvidge clicking on the button changes the entire html with the new button and the class on it changes as well.

![subscribe](https://user-images.githubusercontent.com/2583394/215242474-59126b74-5dc2-463e-99a4-5508e4d466a0.gif)

Let me know if you are seeing any error messages in your browser

**Comment by NatashaSelvidge** [comment]
I'm having some trouble with the subscribe button. When the user clicks the button, it doesn't change to unsubscribe like it's supposed to. The error I am getting is 

Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10

Thank you for your help.🙏

**Comment by barisusakli** [comment]
`at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10 ` this doesn't look like a file we have in nodebb. What does it show when you click on it? Maybe some third party code is interefering. Maybe search your code base for `processResponse` I don't see that function in our code.

**Comment by NatashaSelvidge** [comment]
Yes, its on my end. Sorry about that thank you so much again for your time. 😊

**Comment by barisusakli** [comment]
@NatashaSelvidge no worries 👍🏼
