### ISSUE TITLE
Not working on latest release 0.9

### ISSUE THREAD

**Issue by whittssg** [NodeBB/nodebb-plugin-category-notifications#3]
I tried this plugin and it installs fine but it doesnt seem to notify by email when a new topic created in a category that is already been watched (my dev site has all categories watched by default). I am using a  smtp emailer pluign which works fine when testing from the email screen.. even when i select this plugins emails template it works fine.. but no emails are sent when new topics are created.. the loading icon in the top left does seem to spin forever when this plugin is activated. Thanks

**Comment by ljhardy** [comment]
Right.  Not working with 0.9.3.

**Comment by barisusakli** [comment]
0.9.3 is pretty old please update to 1.1.0+
