### ISSUE TITLE
Untranslatable strings in /lib/categoryNotifications.js

### ISSUE THREAD

**Issue by globalcow** [NodeBB/nodebb-plugin-category-notifications#5]
In https://github.com/NodeBB/nodebb-plugin-category-notifications/blob/master/lib/categoryNotifications.js lines 114 and 170 the strings 'New topic in' and 'New reply in' are used and cannot be translated.

**Comment by jiangcaiyang** [comment]
And in addition, in `client.js`, `Unsubscribe` and `Subcribe` are not translated.
