### ISSUE TITLE
Plugin Configuration page not shown

### ISSUE THREAD

**Issue by wirepatch** [NodeBB/nodebb-plugin-category-notifications#9]
Both installation and activation on an otherwise flawless Nodebb 1.10.1 installation works. When trying to configure the plugin using Dashboard --> Plugin  subsequently selecting sub item »Category notifications« only shows an endless spinner and never any options to be configured.

Server System: 

```
# cat /etc/issue
Ubuntu 18.04.1 LTS

# node -v
v8.12.0

# npm -v
6.4.1
```

**Comment by barisusakli** [comment]
Did you run `./nodebb build` and restart?

**Comment by wirepatch** [comment]
Thanks for the hint solving the problem! I only did a `./nodebb restart`.
